name: second workflow to print ascii artwork

on: push

jobs:
    ascii-artwork-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            
            - name: install cowsay
              run: sudo apt-get install cowsay -y

            - name: execute cowsay cmd
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" > dragon.txt

            - name: dragon file exists
              run: grep -i "dragon" dragon.txt
            
            - name: read dragon.txt file
              run: cat dragon.txt

            - name: list repo files
              run: ls -ltr
