name: second workflow to print ascii artwork

on: push

jobs:
    ascii-artwork-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            
            - name: install cowsay
              run: apt install cowsay

            - name: execute cowsay cmd
              run: cowsay "text" > dragon.txt

            - name: dragon file exists
              run: ls dragon.txt
            
            - name: read dragon.txt file
              run: cat dragon.txt

            - name: read files
              run: ls -ltra
